[project]
name = "AzureTTSTest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "azure-cognitiveservices-speech>=1.44.0",
    "python-dotenv>=1.0.0",
]
